---
title: "R Notebook"
output: html_notebook
---

```{r}
remotes::install_github("carmonalab/SignatuR")
library(SignatuR)
```

Let's add signatures to SignatuR package.

```{r}
# Load HGCN database
hgnc_dataset <- read.csv("../human_TIL_atlas/aux/hgnc_idsymbolname", sep = "\t")

# Pseudogenes
hgnc_dataset.pseudogenes <- hgnc_dataset[which(hgnc_dataset$locus_group == "pseudogene"),]
pseudogenes <- hgnc_dataset.pseudogenes$symbol
names(pseudogenes) <- hgnc_dataset.pseudogenes$ensembl_gene_id
genes.blacklist <- scGate::genes.blacklist.default
genes.blacklist$Hs$pseudogenes <- pseudogenes

# HSP genes
hgnc_dataset.hsp <- read.csv("../human_TIL_atlas/Signatures/HGCN_Gene_groups/HSP_HGCN.txt", sep = "\t")
hsp.genes <- hgnc_dataset.hsp$Approved.symbol
names(hsp.genes) <- hgnc_dataset.hsp$Ensembl.gene.ID
genes.blacklist$Hs$HSP <- hsp.genes

# IG genes
hgnc_dataset.ig <-  hgnc_dataset[grep("immunoglobulin",hgnc_dataset$locus_type),] 
ig.genes <- hgnc_dataset.ig$symbol
names(ig.genes) <- hgnc_dataset.ig$ensembl_gene_id
genes.blacklist$Hs$IG <- ig.genes

# IFN genes
hgnc_dataset.ifn <- hgnc_dataset[union(grep("interferon",hgnc_dataset$name),grep("interferon",hgnc_dataset$alias_name)),] 
ifn.genes <- hgnc_dataset.ifn$symbol
names(ifn.genes) <- hgnc_dataset.ifn$ensembl_gene_id
genes.blacklist$Hs$IFN <- ifn.genes

# non-coding genes
hgnc_dataset.nc <-  hgnc_dataset[grep("non-coding",hgnc_dataset$locus_group),] 
nc.genes <- hgnc_dataset.nc$symbol
names(nc.genes) <- hgnc_dataset.nc$ensembl_gene_id
genes.blacklist$Hs$nc <- nc.genes

# Ribosomal genes
hgnc_dataset.ribo <- read.csv("../human_TIL_atlas/Signatures/HGCN_Gene_groups/Ribo_protein_HGCN.txt", sep = "\t")
ribo.genes <- hgnc_dataset.ribo$Approved.symbol
names(ribo.genes) <- hgnc_dataset.ribo$Ensembl.gene.ID
genes.blacklist$Hs$Ribo <- ribo.genes

# # Histone genes
# hgnc_dataset.histone <- read.csv("Signatures/HGCN_Gene_groups/Histones_HGCN.txt", sep = "\t")
# histone.genes <- hgnc_dataset.histone$Approved.symbol
# names(histone.genes) <- hgnc_dataset.histone$Ensembl.gene.ID
# genes.blacklist$Hs$Histone <- histone.genes
```

```{r}
# Add every geneset to the SignatuR database
SignatuR <- AddSignature(SignatuR,
	node=SignatuR$Hs$Blocklists,name="Pseudogenes",
	reference="Pseudogenes",
	signature=pseudogenes)

SignatuR <- AddSignature(SignatuR,
	node=SignatuR$Hs$Blocklists,name="HSP",
	reference="HSP",
	signature=hsp.genes)

SignatuR <- AddSignature(SignatuR,
	node=SignatuR$Hs$Compartments,name="Immunoglobulins",
	reference="Immunoglobulins",
	signature=ig.genes)

SignatuR <- AddSignature(SignatuR,
	node=SignatuR$Hs$Programs,name="IFN",
	reference="IFN",
	signature=ifn.genes)

SignatuR <- AddSignature(SignatuR,
	node=SignatuR$Hs$Blocklists,name="Non-coding",
	reference="Non-coding",
	signature=nc.genes)

SignatuR <- AddSignature(SignatuR,
	node=SignatuR$Hs$Compartments,name="Ribo",
	reference="Ribo",
	signature=ribo.genes)

# Save updated database
usethis::use_data(SignatuR, overwrite = TRUE)

```
